config/routes.rb
Schedule::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"
  
  get "log_out" => "sessions#destroy", :as => "log_out"

  resources :sessions
  resources :users
  resources :shifts
  resources :holiday_calendars

  

   root :to => 'shifts#index'

end

app/models/holiday_calendar.rb
class HolidayCalendar < ActiveRecord::Base
   attr_accessible :holiday_date, :holiday_reason


	validates :holiday_date, uniqueness: true,presence:true
	validates :holiday_reason, presence:true


end

app/models/shift.rb
class Shift < ActiveRecord::Base
  attr_accessible :name, :shift_date, :user_id
	
	belongs_to :user
#	validates :name, presence: true
	validates :shift_date, presence: true
	validate :shift_date_cannot_be_past	
	validate :shift_date_cannot_be_holiday
	def shift_date_cannot_be_past
		if shift_date.present? && shift_date < Date.today
			errors.add(:shift_date, "Date already passed!")
		end
	end
	
	def shift_date_cannot_be_holiday
		holiday = HolidayCalendar.where("holiday_date = ?", shift_date)
                if holiday.present? 
			errors.add(:holiday, "Holiday cannont be the shift date!")
		end
	end 

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
 #before_save :encrypt_password

	has_many :shifts

  	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates :email, uniqueness: true, presence: true
	#validates_presence_of :email
	#validates_uniqueness_of :email
	#validates_foreign_key :email
 

  def self.authenticate(email, password)
	user = find_by_email(email)
	if user && user.password == password
	   user
	end
  end  


 #def encrypt_password
 #if password.present?
 #	self.password_salt = Bcrypt::Engine.generate_salt
 #      self.password_hash = Bcrypt::Engine.hash_secret(password, password_salt) #end
 #end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

end

app/controllers/holiday_calendars_controller.rb
class HolidayCalendarsController < ApplicationController
 def new
	@holiday_calendar = HolidayCalendar.new
 end

  def create
	holiday_calendar_props = params[:holiday_calendar]
	@holiday_calendar = HolidayCalendar.new(holiday_calendar_props)
	if @holiday_calendar.save
		redirect_to holiday_calendars_path, :notice => "Holiday is Created!"
	else
		render :new
	end
  end

  def index
		@holiday_calendars = HolidayCalendar.order('created_at DESC')
  end

  def edit
		@holiday_calendar = HolidayCalendar.find(params[:id])
  end
  
  def show
		@holiday_calendar = HolidayCalendar.find(params[:id])
		render :layout => 'application'
  end
  def update
		@holiday_calendar = HolidayCalendar.find(params[:id])
		holiday_calendar_props = params[:holiday_calendar]
		if @holiday_calendar.update_attributes(holiday_calendar_props)
			redirect_to holiday_calendar_path(@holiday_calendar), :notice => "Your holiday has been updated!"
		else
			render :edit
		end
  end

  def destroy
	@holiday_calendar = HolidayCalendar.find(params[:id])
	if @holiday_calendar.destroy
		redirect_to holiday_calendars_path, :notice => "Holiday has ben deleted!"
	else
		redirect_to holiday_calendars_path, :notice => "Holiday has not been deleted!"
	end
  end 	


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	user = User.authenticate(params[:email], params[:password])
	
	if user
		session[:user_id] = user.id
		redirect_to root_url, :notice => "Logged In"
	else
		flash.now.alert = "Invalid Email/Password!"
		render "new"
	end
  end

  def destroy
	session[:user_id] = nil
	redirect_to log_in_url, :notice => "Logged out!"
  end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController

	def new
		@shift = Shift.new
		@shift.user = current_user
	end
	
	def create
		shift_props = params[:shift]
		@shift = Shift.new(shift_props)
		if @shift.save
			redirect_to shifts_path, :notice => "Shift is created"
		else

		render :new
		end
	end
	
	def index
	#	@shifts = Shift.order('created_at DESC')
		@shifts = current_user.shifts	
	end
	
	def show
		@shift = Shift.find(params[:id])
		render :layout => 'application'
	end
	
	def update
		@shift = Shift.find(params[:id])
		shift_props = params[:shift]
		if @shift.update_attributes(shift_props)
			redirect_to shift_path(@shift), :notice => "Your Shift has been updated!"
		else
			
			render :edit
		end
	end

	def edit
		@shift = Shift.find(params[:id])
	end

	def destroy
		@shift = Shift.find(params[:id])
		if @shift.destroy
			redirect_to shifts_path, :notice => "Shift has been deleted!"
		else
			redirect_to shifts_path, :notice => "Shift is not deleted!"
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

	@user = User.new
  end


  def create
	@user = User.new(params[:user])
	if @user.save
		redirect_to root_url, :notice => "Signed Up!"
	else
		render "new"
	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/holiday_calendars_helper.rb
module HolidayCalendarsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/holiday_calendars/create.html.erb
<b> Holiday has been created! </b>

app/views/holiday_calendars/destroy.html.erb
<b> Holiday has been <%= @status? "Has been deleted!" | "cannot be deleted!"%> </b>

app/views/holiday_calendars/edit.html.erb
<b> Holiday Edit Form </b>

<%= render 'form' %>

<%= link_to "Back to holidays", holiday_calendars_path%> | <%= link_to "Show", holiday_calendar_path(@holiday_calendar)%> | <%= link_to "Delete", holiday_calendar_path(@holiday_calendar), :method => "DELETE" %>

app/views/holiday_calendars/index.html.erb
<h1>Holidays #index</h1>
<p> <%= flash[:notice] %> </p><br/>
<div style="float:right;"><%= link_to "Create New Holiday", new_holiday_calendar_path %>
</div>

<b> All Holidays </b>
<% @holiday_calendars.each do |holiday_calendar| %>
	<div style="margin:5px;border-bottom:2px solid red;">
	<%= holiday_calendar.holiday_reason %><br/>
	<%= holiday_calendar.holiday_date%> <br/>
	<%=  holiday_calendar.created_at%>
	<br/>
	<%= link_to "Edit", edit_holiday_calendar_path(holiday_calendar) %> |<%= link_to "Show", holiday_calendar_path(holiday_calendar) %> | <%= link_to "Delete", holiday_calendar_path(holiday_calendar), :method => 'DELETE' %>	

	</div>
<% end %>

app/views/holiday_calendars/new.html.erb
<b> This is the new Holiday Creation Form</b>


<%= render 'form' %>

app/views/holiday_calendars/show.html.erb
<p> <%= flash[:notice] %> </p> <br/><br/>

<b><%= @holiday_calendar.holiday_reason %> </b>
<br/>
<b><%= @holiday_calendar.holiday_date %> </b>
<br/>

<%= link_to "Back to holidays", holiday_calendars_path %> | <%= link_to "Edit", edit_holiday_calendar_path(@holiday_calendar) %> | <%= link_to "Delete", holiday_calendar_path(@holiday_calendar), :method =>"DELETE" %>

app/views/holiday_calendars/update.html.erb
<b> Holiday has been update successfully! </b>

<b> Holiday Reason: </b><%= @holiday_calendar.holiday_reason %> <br/>
<b> Holiday Date: </b><%= @holiday_calendar.holiday_date %> <br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Schedule</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
	<%= current_user.email %>

	<%= link_to "Log out", log_out_path %>
<%  end %>

<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, :id => "flash_#{name}" %>

<% end %>


<%= yield %>

</body>
</html>

app/views/shifts/create.html.erb
<b> Shift has been created! </b>

app/views/shifts/destroy.html.erb
<b> Your shift entry <%= @status? "has been deleted" : " can not be deleted" %> </b>

app/views/shifts/edit.html.erb
<b> Shift Edit Form </b>


<%= render 'form' %>

<%= link_to "Back to list", shifts_path%> | <%= link_to "Show", shift_path(@shift)%> | <%= link_to "Delete", shift_path(@shift), :method => "DELETE"%>

app/views/shifts/index.html.erb
<h1>Schedules</h1>
<p> <%= flash[:notice] %> </p><br/>
<div style="float:right;"><%= link_to "Create New Schedule", new_shift_path %>
</div>

<b> All Shifts </b>
<% @shifts.each do |shift| %>
	<div style="margin:5px;border-bottom:2px solid red;">
	<%= shift.name %><br/>
	<%= shift.shift_date%> <br/>
	<%=  shift.created_at%> <br/>
	 User Id is <%= shift.user_id%>
  <br/><br/>	 <%= shift.user.email %>
	<br/>


	
<%= link_to "Edit", edit_shift_path(shift) %> | <%= link_to "Show", shift_path(shift) %> | <%= link_to "Delete", shift_path(shift), :method => "DELETE" %>
	</div>
<% end %>

app/views/shifts/new.html.erb
<br/><br/><b> This is the new Schedule Creation Form</b>


<%= render 'form' %>

app/views/shifts/show.html.erb
<p><%= flash[:notice] %> </p> <br/>

<b><%=@shift.name %></b>
<br/>
<p><%= @shift.shift_date %></p>


<%= link_to "Back to Index", shifts_path %> | <%= link_to "Edit", edit_shift_path(@shift) %> | <%= link_to "Delete", shift_path(@shift), :method => "DELETE" %>

app/views/shifts/update.html.erb
<b> Your Shift has been updated </b>

<b> Name: </b> <%= @shift.name %> <br/>
<b> Shift Date </b> <%= @shift.shift_date %> <br/>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= render 'form' %>
<br/><br/>
<%= link_to "Log in", { controller: "sessions", action: "new" } %>